name: dsci522-env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5
  - altair=5.3.0
  - attrs=25.4.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - icu=75.1
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcxx=21.1.6
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.51.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - markupsafe=3.0.3
  - ncurses=6.5
  - numpy=2.3.5
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.2.2
  - pip=25.3
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - readline=8.2
  - referencing=0.37.0
  - rpds-py=0.29.0
  - setuptools=80.9.0
  - six=1.17.0
  - tk=8.6.13
  - toolz=1.1.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - zipp=3.23.0
prefix: /opt/anaconda3/envs/dsci522-env
